export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  PAYLOAD_TOO_LARGE: 413,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const RESPONSE_CODE = {
  SUCCESS: "SUCCESS",
  CREATED: "CREATED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  EXTRACTION_FAILED: "EXTRACTION_FAILED",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",

  SERVER_ERROR: "SERVER_ERROR",
} as const;

export type ResponseCode = (typeof RESPONSE_CODE)[keyof typeof RESPONSE_CODE];


export const PRISMA_ERROR_CODE = {
  UNIQUE_CONSTRAINT_VIOLATION: "P2002",
  RECORD_NOT_FOUND: "P2025",
} as const;
